version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  server:
    build: ./portDomainService
    env_file:
      - .env
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
  client:
    build: ./clientAPI
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - server
    restart: on-failure
