// Code generated by protoc-gen-go. DO NOT EDIT.
// source: port-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Taks we have to do
type Port struct {
	PortID               string   `protobuf:"bytes,1,opt,name=portID,proto3" json:"portID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetPortID() string {
	if m != nil {
		return m.PortID
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JSONPort struct {
	Api                  string           `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Ports                map[string]*Port `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JSONPort) Reset()         { *m = JSONPort{} }
func (m *JSONPort) String() string { return proto.CompactTextString(m) }
func (*JSONPort) ProtoMessage()    {}
func (*JSONPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{1}
}

func (m *JSONPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONPort.Unmarshal(m, b)
}
func (m *JSONPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONPort.Marshal(b, m, deterministic)
}
func (m *JSONPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONPort.Merge(m, src)
}
func (m *JSONPort) XXX_Size() int {
	return xxx_messageInfo_JSONPort.Size(m)
}
func (m *JSONPort) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONPort.DiscardUnknown(m)
}

var xxx_messageInfo_JSONPort proto.InternalMessageInfo

func (m *JSONPort) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *JSONPort) GetPorts() map[string]*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

// Request data to create new Port
type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Port                 *Port    `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetPort() *Port {
	if m != nil {
		return m.Port
	}
	return nil
}

// Contains data of created Port
type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	PortID               string   `protobuf:"bytes,2,opt,name=portID,proto3" json:"portID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetPortID() string {
	if m != nil {
		return m.PortID
	}
	return ""
}

// Request data to read Port
type ReadRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	PortID               string   `protobuf:"bytes,2,opt,name=portID,proto3" json:"portID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{4}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadRequest) GetPortID() string {
	if m != nil {
		return m.PortID
	}
	return ""
}

// Contains port data specified in by ID request
type ReadResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Port                 *Port    `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{5}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetPort() *Port {
	if m != nil {
		return m.Port
	}
	return nil
}

// Request data to update port
type LoadFromJSONRequest struct {
	Api                  string           `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Ports                map[string]*Port `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoadFromJSONRequest) Reset()         { *m = LoadFromJSONRequest{} }
func (m *LoadFromJSONRequest) String() string { return proto.CompactTextString(m) }
func (*LoadFromJSONRequest) ProtoMessage()    {}
func (*LoadFromJSONRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{6}
}

func (m *LoadFromJSONRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadFromJSONRequest.Unmarshal(m, b)
}
func (m *LoadFromJSONRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadFromJSONRequest.Marshal(b, m, deterministic)
}
func (m *LoadFromJSONRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadFromJSONRequest.Merge(m, src)
}
func (m *LoadFromJSONRequest) XXX_Size() int {
	return xxx_messageInfo_LoadFromJSONRequest.Size(m)
}
func (m *LoadFromJSONRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadFromJSONRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadFromJSONRequest proto.InternalMessageInfo

func (m *LoadFromJSONRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoadFromJSONRequest) GetPorts() map[string]*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

// Contains status of update operation
type LoadFromJSONResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Skipped              int64    `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Records              int64    `protobuf:"varint,5,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadFromJSONResponse) Reset()         { *m = LoadFromJSONResponse{} }
func (m *LoadFromJSONResponse) String() string { return proto.CompactTextString(m) }
func (*LoadFromJSONResponse) ProtoMessage()    {}
func (*LoadFromJSONResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{7}
}

func (m *LoadFromJSONResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadFromJSONResponse.Unmarshal(m, b)
}
func (m *LoadFromJSONResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadFromJSONResponse.Marshal(b, m, deterministic)
}
func (m *LoadFromJSONResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadFromJSONResponse.Merge(m, src)
}
func (m *LoadFromJSONResponse) XXX_Size() int {
	return xxx_messageInfo_LoadFromJSONResponse.Size(m)
}
func (m *LoadFromJSONResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadFromJSONResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadFromJSONResponse proto.InternalMessageInfo

func (m *LoadFromJSONResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoadFromJSONResponse) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *LoadFromJSONResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *LoadFromJSONResponse) GetSkipped() int64 {
	if m != nil {
		return m.Skipped
	}
	return 0
}

func (m *LoadFromJSONResponse) GetRecords() int64 {
	if m != nil {
		return m.Records
	}
	return 0
}

// Request data to delete port
type DeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	PortID               string   `protobuf:"bytes,2,opt,name=portID,proto3" json:"portID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetPortID() string {
	if m != nil {
		return m.PortID
	}
	return ""
}

// Contains status of delete operation
type DeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	PortID               string   `protobuf:"bytes,2,opt,name=portID,proto3" json:"portID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteResponse) GetPortID() string {
	if m != nil {
		return m.PortID
	}
	return ""
}

// Request data to read all ports
type ReadAllRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{10}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// Contains list of all ports
type ReadAllResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Ports                []*Port  `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4e95c17ee32355, []int{11}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadAllResponse) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func init() {
	proto.RegisterType((*Port)(nil), "v1.Port")
	proto.RegisterType((*JSONPort)(nil), "v1.JSONPort")
	proto.RegisterMapType((map[string]*Port)(nil), "v1.JSONPort.PortsEntry")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "v1.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "v1.ReadResponse")
	proto.RegisterType((*LoadFromJSONRequest)(nil), "v1.LoadFromJSONRequest")
	proto.RegisterMapType((map[string]*Port)(nil), "v1.LoadFromJSONRequest.PortsEntry")
	proto.RegisterType((*LoadFromJSONResponse)(nil), "v1.LoadFromJSONResponse")
	proto.RegisterType((*DeleteRequest)(nil), "v1.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "v1.DeleteResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "v1.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "v1.ReadAllResponse")
}

func init() { proto.RegisterFile("port-service.proto", fileDescriptor_6c4e95c17ee32355) }

var fileDescriptor_6c4e95c17ee32355 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0x7e, 0x9a, 0x8d, 0x93, 0xad, 0x1b, 0x1e, 0x62, 0x51, 0x84, 0xa6, 0xc9, 0x57, 0xe3,
	0x62, 0x99, 0x16, 0x2e, 0x18, 0xbd, 0x00, 0x8d, 0x0d, 0x24, 0x10, 0x02, 0x94, 0x3d, 0x41, 0x68,
	0x7c, 0x51, 0x35, 0xab, 0x83, 0x9d, 0x46, 0xea, 0x53, 0x00, 0x0f, 0xc1, 0x7b, 0xa2, 0x63, 0x3b,
	0x24, 0xa1, 0x75, 0x25, 0x2e, 0x76, 0x53, 0xe5, 0xfc, 0x7c, 0xdf, 0x39, 0xfe, 0x3e, 0xbb, 0x40,
	0x2a, 0x2e, 0xea, 0x73, 0xc9, 0x44, 0x33, 0x9b, 0xb2, 0xa4, 0x12, 0xbc, 0xe6, 0xc4, 0x6d, 0x2e,
	0x69, 0x0a, 0xfe, 0x57, 0x2e, 0x6a, 0xf2, 0x14, 0x02, 0xec, 0xf8, 0x70, 0x1b, 0x39, 0xa7, 0xce,
	0xd9, 0xa3, 0xcc, 0x44, 0x84, 0x80, 0xbf, 0xc8, 0xef, 0x59, 0xe4, 0xaa, 0xac, 0xfa, 0xa6, 0x3f,
	0x1c, 0xd8, 0xfd, 0x78, 0xf7, 0xe5, 0xb3, 0x02, 0x1e, 0x82, 0x97, 0x57, 0x33, 0x83, 0xc2, 0x4f,
	0x72, 0x0e, 0x23, 0x04, 0xcb, 0xc8, 0x3d, 0xf5, 0xce, 0xc2, 0xf4, 0x38, 0x69, 0x2e, 0x93, 0xb6,
	0x3d, 0xc1, 0x1f, 0xf9, 0x6e, 0x51, 0x8b, 0x55, 0xa6, 0xbb, 0xe2, 0xb7, 0x00, 0x5d, 0x12, 0xe9,
	0xe6, 0x6c, 0xd5, 0xd2, 0xcd, 0xd9, 0x8a, 0x9c, 0xc0, 0xa8, 0xc9, 0xcb, 0xa5, 0x5e, 0x21, 0x4c,
	0x77, 0x91, 0x0e, 0x01, 0x99, 0x4e, 0x4f, 0xdc, 0x2b, 0x87, 0xbe, 0x81, 0xfd, 0x1b, 0xc1, 0xf2,
	0x9a, 0x65, 0xec, 0xfb, 0x92, 0xc9, 0x4d, 0x5b, 0x3d, 0x03, 0x1f, 0xe7, 0xad, 0xb1, 0xa8, 0x2c,
	0x9d, 0xc0, 0xb8, 0x25, 0x90, 0x15, 0x5f, 0x48, 0xb6, 0x81, 0xa1, 0x93, 0xc8, 0xed, 0x4b, 0x44,
	0x5f, 0x42, 0x98, 0xb1, 0xbc, 0xb0, 0x8f, 0xb6, 0x01, 0x5f, 0xc3, 0x9e, 0x06, 0x5a, 0x47, 0x6e,
	0x5f, 0xfa, 0xb7, 0x03, 0x47, 0x9f, 0x78, 0x5e, 0xbc, 0x17, 0xfc, 0x1e, 0x05, 0xb6, 0x6f, 0x70,
	0x35, 0xb4, 0x84, 0x22, 0xd1, 0x06, 0xe4, 0x03, 0xb9, 0xf3, 0xd3, 0x81, 0x27, 0xc3, 0x69, 0xd6,
	0x03, 0x47, 0xb0, 0x33, 0x55, 0x3e, 0x14, 0x8a, 0xd0, 0xcb, 0xda, 0x10, 0x2b, 0xcb, 0xaa, 0x50,
	0x15, 0x4f, 0x57, 0x4c, 0x88, 0x15, 0x39, 0x9f, 0x55, 0x15, 0x2b, 0x22, 0x5f, 0x57, 0x4c, 0x88,
	0x15, 0xc1, 0xa6, 0x5c, 0x14, 0x32, 0x1a, 0xe9, 0x8a, 0x09, 0xe9, 0x2b, 0xd8, 0xbf, 0x65, 0x25,
	0xdb, 0x76, 0x61, 0x6c, 0xae, 0x4d, 0x60, 0xdc, 0x42, 0xff, 0xfb, 0xaa, 0x50, 0x18, 0xa3, 0xe3,
	0xd7, 0x65, 0x69, 0x9d, 0x4b, 0x6f, 0xe0, 0xe0, 0x6f, 0x8f, 0x75, 0xc0, 0xc9, 0xd0, 0xd0, 0x9e,
	0xec, 0x2a, 0x9d, 0xfe, 0x72, 0x21, 0xc4, 0xf8, 0x4e, 0x3f, 0x78, 0x72, 0x01, 0x81, 0xbe, 0xdf,
	0xe4, 0x31, 0xb6, 0x0e, 0x1e, 0x4b, 0x4c, 0xfa, 0x29, 0x33, 0xf2, 0x1a, 0xf6, 0xfa, 0x96, 0x91,
	0x63, 0xcb, 0x95, 0x89, 0xa3, 0xf5, 0x82, 0xa1, 0x78, 0x0e, 0x3e, 0x1e, 0x84, 0x1c, 0x60, 0x47,
	0xef, 0x85, 0xc4, 0x87, 0x5d, 0xc2, 0xb4, 0x5e, 0x40, 0xa0, 0x35, 0xd5, 0xeb, 0x0d, 0xac, 0xd1,
	0xeb, 0xfd, 0x23, 0x79, 0x0a, 0x3b, 0x46, 0x24, 0x42, 0x5a, 0xb6, 0x4e, 0xd5, 0xf8, 0x68, 0x90,
	0xd3, 0x98, 0x6f, 0x81, 0xfa, 0xd7, 0x7b, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xc0, 0x4d,
	0xb2, 0x0b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	LoadFromJSON(ctx context.Context, in *LoadFromJSONRequest, opts ...grpc.CallOption) (*LoadFromJSONResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
}

type portServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortServiceClient(cc *grpc.ClientConn) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.PortService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) LoadFromJSON(ctx context.Context, in *LoadFromJSONRequest, opts ...grpc.CallOption) (*LoadFromJSONResponse, error) {
	out := new(LoadFromJSONResponse)
	err := c.cc.Invoke(ctx, "/v1.PortService/LoadFromJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/v1.PortService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.PortService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := c.cc.Invoke(ctx, "/v1.PortService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServiceServer is the server API for PortService service.
type PortServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	LoadFromJSON(context.Context, *LoadFromJSONRequest) (*LoadFromJSONResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
}

func RegisterPortServiceServer(s *grpc.Server, srv PortServiceServer) {
	s.RegisterService(&_PortService_serviceDesc, srv)
}

func _PortService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PortService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_LoadFromJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadFromJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).LoadFromJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PortService/LoadFromJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).LoadFromJSON(ctx, req.(*LoadFromJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PortService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PortService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PortService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PortService_Create_Handler,
		},
		{
			MethodName: "LoadFromJSON",
			Handler:    _PortService_LoadFromJSON_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _PortService_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PortService_Delete_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _PortService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "port-service.proto",
}
